include:
 - compose.yml
services:
  # needed for aws s3 storage testing
  minio:
    image: "minio/minio:latest"
    container_name: "minio_${APP_NAME}"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
    environment:
      MINIO_ROOT_USER: laravel
      # at least 8 chars
      MINIO_ROOT_PASSWORD: laravelminio
    volumes:
      - "./docker/volumes/minio/data:/data/minio"
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      retries: 3
      timeout: 5s
  # needed for mails testing
  mailpit:
    container_name: "mailpit_${APP_NAME}"
    image: "axllent/mailpit:latest"
    ports:
    - "${FORWARD_MAILPIT_PORT:-1025}:1025"
    - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
