name: Laravel deploy DEVELOP

on:
  push:
    branches: 
      - develop

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_PASSWORD: geohub2
          POSTGRES_DB: geohub2
          POSTGRES_USER: geohub2
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cp .env-example .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Add hosts to /etc/hosts
      run: sudo echo "127.0.0.1 db" | sudo tee -a /etc/hosts
    - name: Migrate
      run: php artisan migrate
      env:
          PGPASSWORD: geohub2
    - name: Laravel Tests
      run: php artisan test
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTDEV }}
        username: ${{ secrets.USERNAMEDEV }}
        port: ${{ secrets.PORTDEV }}
        key: ${{ secrets.SSHKEYDEV }}
        script: "cd /root/html/geohub && git pull && docker exec php81_geohub bash scripts/deploy_dev.sh"
