on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Make a release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/release-please-action
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
